Wed Dec 06 20:48:19 EST 2017 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Wed Dec 06 20:48:20 EST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0160-2ea8-c198-ffff80c818b1 
on database directory C:\Users\admin\Desktop\ibas\ibasdb with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_65/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_65-b17
user.dir=C:\Program Files\Java\jdk1.8.0_65\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\admin\Desktop\ibas
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Dec 06 20:48:22 EST 2017:
Shutting down instance a816c00e-0160-2ea8-c198-ffff80c818b1 on database directory C:\Users\admin\Desktop\ibas\ibasdb with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Wed Dec 06 20:48:22 EST 2017 Thread[DRDAConnThread_2,5,main] (DATABASE = ibasdb), (DRDAID = {2}), Database 'ibasdb' shutdown.
----------------------------------------------------------------
Wed Dec 06 20:48:47 EST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a65c80ac-0160-2ea8-c198-ffff80c818b1 
on database directory C:\Users\admin\Desktop\ibas\ibasdb with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_65/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_65-b17
user.dir=C:\Program Files\Java\jdk1.8.0_65\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\admin\Desktop\ibas
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Dec 06 21:45:19 EST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance f7fd413a-0160-2ea8-c198-ffff80c818b1 
on database directory C:\Users\admin\Desktop\ibas\ibas with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_65/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_65-b17
user.dir=C:\Program Files\Java\jdk1.8.0_65\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\admin\Desktop\ibas
Database Class Loader started - derby.database.classpath=''
Wed Dec 06 21:52:03 EST 2017 Thread[DRDAConnThread_4,5,main] (XID = 380), (SESSIONID = 2), (DATABASE = ibasdb), (DRDAID = {29}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Dec 06 21:52:03 EST 2017 Thread[DRDAConnThread_4,5,main] (DATABASE = ibasdb), (DRDAID = {29}), Connection authentication failure occurred.  Reason: Invalid authentication..
----------------------------------------------------------------
Wed Dec 06 21:52:07 EST 2017:
Shutting down instance f7fd413a-0160-2ea8-c198-ffff80c818b1 on database directory C:\Users\admin\Desktop\ibas\ibas with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Wed Dec 06 21:52:07 EST 2017 Thread[DRDAConnThread_3,5,main] (DATABASE = ibas), (DRDAID = {30}), Database 'ibas' shutdown.
----------------------------------------------------------------
Wed Dec 06 21:52:28 EST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance b72cc21e-0160-2ea8-c198-ffff80c818b1 
on database directory C:\Users\admin\Desktop\ibas\ibas with class loader sun.misc.Launcher$AppClassLoader@5e2de80c 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_65/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_65-b17
user.dir=C:\Program Files\Java\jdk1.8.0_65\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\admin\Desktop\ibas
Database Class Loader started - derby.database.classpath=''
